
services:
  db:
    image: postgres:16-alpine
    container_name: sophi_ia_db_prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - sophi_network

  web:
    build: .
    container_name: sophi_ia_web_prod
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 4
      "
    volumes:
      - static_volume_prod:/app/staticfiles
      - media_volume_prod:/app/media
    ports:
      - "8000:8000"
    environment:
      DEBUG: "False"
      DATABASE_ENGINE: django.db.backends.postgresql
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
    depends_on:
      - db
    restart: always
    networks:
      - sophi_network

volumes:
  postgres_data_prod:
  static_volume_prod:
  media_volume_prod:

networks:
  sophi_network:
    driver: bridge
